export const ADD_INGREDIANT="ADD_INGREDIANT";
export const REMOVE_INGREDIANT="REMOVE_INGREDIANT";
export const SET_INGREDIANT="SET_INGREDIANT";
export const FETCH_INGREDIANT_FAILED='FETCH_INGREDIANT_FAILED'

export const PURCHASE_BURGER_START='PURCHASE_BURGER_START'
export const  PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS'
export const  PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL'
export const  PURCHASE_INIT="PURCHASE_INIT"




export const AUTH_START="AUTH_START"
export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_FAIL="AUTH_FAIL"
export const AUTH_LOGOUT="AUTH_LOGOUT"

export const SET_AUTH_REDIRECT_PATH="SET_AUTH_REDIRECT_PATH"
export const  FETCH_ORDER="FETCH_ORDER"